services:
  db:
    image: pgvector/pgvector:pg16
    container_name: titan_db
    restart: always
    environment:
      POSTGRES_USER: titan_user
      POSTGRES_PASSWORD: titan_password
      POSTGRESS_DB: titan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: titan_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@titan.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: